/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#dae2fd',
        'on-tertiary': '#ffffff',
        'surface-container': '#e5eeff',
        'background': '#f8f9ff',
        'inverse-surface': '#213145',
        'secondary-fixed-dim': '#6bd8cb',
        'tertiary-container': '#2a1700',
        'on-primary-fixed-variant': '#3f465c',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#653e00',
        'error-container': '#ffdad6',
        'surface-dim': '#cbdbf5',
        'on-surface-variant': '#45464d',
        'tertiary': '#000000',
        'tertiary-fixed': '#ffddb8',
        'brand-red-legacy': '#D24D33',
        'tertiary-fixed-dim': '#ffb95f',
        'secondary-fixed': '#89f5e7',
        'background-primary': '#FFFFFF',
        'primary-container': '#131b2e',
        'surface-container-low': '#eff4ff',
        'primary-fixed-dim': '#bec6e0',
        'inverse-primary': '#bec6e0',
        'on-secondary-fixed-variant': '#005049',
        'surface-dark': '#1E293B',
        'on-secondary-fixed': '#00201d',
        'background-secondary': '#F8FAFC',
        'on-tertiary-container': '#b87500',
        'on-surface': '#0b1c30',
        'on-background': '#0b1c30',
        'surface-tint': '#565e74',
        'on-tertiary-fixed': '#2a1700',
        'surface-bright': '#f8f9ff',
        'on-primary-fixed': '#131b2e',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#d3e4fe',
        'secondary-container': '#86f2e4',
        'surface-container-highest': '#d3e4fe',
        'surface-container-high': '#dce9ff',
        'success': '#10B981',
        'on-primary-container': '#7c839b',
        'secondary': '#006a61',
        'on-primary': '#ffffff',
        'surface': '#f8f9ff',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-container': '#006f66',
        'outline': '#76777d',
        'on-error-container': '#93000a',
        'outline-variant': '#c6c6cd',
        'error': '#EF4444',
        'primary': '#000000',
      },
      fontFamily: {
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '500' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
